url: https://frantisekkracmar.github.io
baseurl: /beewolf

# Site settings
title: Beewolf
email: beewolfcz@gmail.com
description: "Vítejte na našich stránkách. Naleznete zde služby, které nabízíme."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/beewolfcz
 # - title: facebook
 #   url:
 # - title: stack-overflow
 #   url: http://stackoverflow.com/questions/tagged/jekyll
 # - title: bitbucket 
 #   url: http://bitbucket.org/jekyll
 # - title: github
 #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Hořice 50801, Czech republic

# Build settings
markdown: kramdown
permalink: pretty